# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wipnote < Formula
  desc "Local-first observability and coordination platform for AI-assisted development"
  homepage "https://github.com/shakestzd/wipnote"
  version "0.63.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.63.2/wipnote_0.63.2_darwin_amd64.tar.gz"
      sha256 "b378e6396baf234f7cfddd1cf5c0275050add7df7a1a014f634d579ae49406e2"

      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
        (share/"wipnote").install "antigravity-extension"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.63.2/wipnote_0.63.2_darwin_arm64.tar.gz"
      sha256 "a52a3da5e7bc42752d262ab475b7e563b449651875e3014c52f3e3a6432cea25"

      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
        (share/"wipnote").install "antigravity-extension"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.63.2/wipnote_0.63.2_linux_amd64.tar.gz"
      sha256 "1166785df758daa7ce9188851754e05d1c4ff747994263939ff9c06ff9b9cac5"
      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
        (share/"wipnote").install "antigravity-extension"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.63.2/wipnote_0.63.2_linux_arm64.tar.gz"
      sha256 "6a7bac02364d45e4be4719053389f625276f81033084950648f7a35a8f724b99"
      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
        (share/"wipnote").install "antigravity-extension"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wipnote version")
  end
end
