# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wipnote < Formula
  desc "Local-first observability and coordination platform for AI-assisted development"
  homepage "https://github.com/shakestzd/wipnote"
  version "0.60.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.16/wipnote_0.60.16_darwin_amd64.tar.gz"
      sha256 "ca8faea10c3df06c5ef71d5460c55627e5cad1b3e7f4f00bfb8d4e39c20c16b6"

      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.16/wipnote_0.60.16_darwin_arm64.tar.gz"
      sha256 "364dacbb93b6ae75d9cea0c88de6bfb07468d81c3d60b515a53c296000dd85d6"

      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.16/wipnote_0.60.16_linux_amd64.tar.gz"
      sha256 "7ac68f47c57542949c58f3ce64393bdbc47edf11ce40ffebb0f75af0b939d5ac"
      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.16/wipnote_0.60.16_linux_arm64.tar.gz"
      sha256 "e5cacbe06dc249cc6d542ac456fc5f94e3a061d569a18ee591175ded29e89ba0"
      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wipnote version")
  end
end
