# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wipnote < Formula
  desc "Local-first observability and coordination platform for AI-assisted development"
  homepage "https://github.com/shakestzd/wipnote"
  version "0.60.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.8/wipnote_0.60.8_darwin_amd64.tar.gz"
      sha256 "f10905cee83806c567011c5c560382cbd26e18a4b295f40213ea3915ea2926bc"

      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.8/wipnote_0.60.8_darwin_arm64.tar.gz"
      sha256 "90d0aca2a8322aff6d5979f219e1cfcae3567a8b7b7b259da6bd10e55ddc6364"

      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.8/wipnote_0.60.8_linux_amd64.tar.gz"
      sha256 "c919ef362a0ce900fe0977be62ebe1d7ce984fce497bb041b65b5b2b9d582a5a"
      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shakestzd/wipnote/releases/download/v0.60.8/wipnote_0.60.8_linux_arm64.tar.gz"
      sha256 "036c109d6167afbfb531f8eb5ec3946391afc302b4f17eb98d1b3f4929163404"
      define_method(:install) do
        bin.install "wipnote"
        bin.install_symlink "wipnote" => "wn"
        (share/"wipnote").install "plugin"
        (share/"wipnote").install "codex-marketplace"
        (share/"wipnote").install "gemini-extension"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wipnote version")
  end
end
